google.maps.__gjsload__('geometry', function(_){var ss=function(a,b){return Math.abs(_.Mc(b-a,-180,180))},ts=function(a,b,c,d,e){if(!d){c=ss(a.lng(),c)/ss(a.lng(),b.lng());if(!e)return e=Math.sin(_.gc(a.lat())),e=Math.log((1+e)/(1-e))/2,b=Math.sin(_.gc(b.lat())),_.hc(2*Math.atan(Math.exp(e+c*(Math.log((1+b)/(1-b))/2-e)))-Math.PI/2);a=e.fromLatLngToPoint(a);b=e.fromLatLngToPoint(b);return e.fromPointToLatLng(new _.P(a.x+c*(b.x-a.x),a.y+c*(b.y-a.y))).lat()}e=_.gc(a.lat());a=_.gc(a.lng());d=_.gc(b.lat());b=_.gc(b.lng());c=_.gc(c);return _.Mc(_.hc(Math.atan2(Math.sin(e)*
Math.cos(d)*Math.sin(c-b)-Math.sin(d)*Math.cos(e)*Math.sin(c-a),Math.cos(e)*Math.cos(d)*Math.sin(a-b))),-90,90)},us=_.n(),vs={containsLocation:function(a,b){var c=_.Mc(a.lng(),-180,180),d=!!b.get("geodesic"),e=b.get("latLngs"),f=b.get("map");f=!d&&f?f.getProjection():null;for(var g=!1,h=0,k=e.getLength();h<k;++h)for(var l=e.getAt(h),m=0,q=l.getLength();m<q;++m){var r=l.getAt(m),u=l.getAt((m+1)%q),v=_.Mc(r.lng(),-180,180),w=_.Mc(u.lng(),-180,180),x=Math.max(v,w);v=Math.min(v,w);(180<x-v?c>=x||c<v:
c<x&&c>=v)&&ts(r,u,c,d,f)<a.lat()&&(g=!g)}return g||vs.isLocationOnEdge(a,b)}};_.cb("PolyGeometry.containsLocation",vs.containsLocation);
vs.isLocationOnEdge=function(a,b,c){c=c||1E-9;var d=_.Mc(a.lng(),-180,180),e=b instanceof _.uh,f=!!b.get("geodesic"),g=b.get("latLngs");b=b.get("map");b=!f&&b?b.getProjection():null;for(var h=0,k=g.getLength();h<k;++h)for(var l=g.getAt(h),m=l.getLength(),q=e?m:m-1,r=0;r<q;++r){var u=l.getAt(r),v=l.getAt((r+1)%m),w=_.Mc(u.lng(),-180,180),x=_.Mc(v.lng(),-180,180),B=Math.max(w,x),E=Math.min(w,x);if(w=1E-9>=Math.abs(_.Mc(w-x,-180,180))&&(Math.abs(_.Mc(w-d,-180,180))<=c||Math.abs(_.Mc(x-d,-180,180))<=
c)){w=a.lat();x=Math.min(u.lat(),v.lat())-c;var F=Math.max(u.lat(),v.lat())+c;w=w>=x&&w<=F}if(w)return!0;if(180<B-E?d+c>=B||d-c<=E:d+c>=E&&d-c<=B)if(u=ts(u,v,d,f,b),Math.abs(u-a.lat())<c)return!0}return!1};_.cb("PolyGeometry.isLocationOnEdge",vs.isLocationOnEdge);var ws={computeHeading:function(a,b){var c=_.ud(a),d=_.vd(a);a=_.ud(b);b=_.vd(b)-d;return _.Mc(_.hc(Math.atan2(Math.sin(b)*Math.cos(a),Math.cos(c)*Math.sin(a)-Math.sin(c)*Math.cos(a)*Math.cos(b))),-180,180)}};_.cb("Spherical.computeHeading",ws.computeHeading);
ws.computeOffset=function(a,b,c,d){b/=d||6378137;c=_.gc(c);var e=_.ud(a);a=_.vd(a);d=Math.cos(b);b=Math.sin(b);var f=Math.sin(e);e=Math.cos(e);var g=d*f+b*e*Math.cos(c);return new _.R(_.hc(Math.asin(g)),_.hc(a+Math.atan2(b*e*Math.sin(c),d-f*g)))};_.cb("Spherical.computeOffset",ws.computeOffset);
ws.computeOffsetOrigin=function(a,b,c,d){c=_.gc(c);b/=d||6378137;d=Math.cos(b);var e=Math.sin(b)*Math.cos(c);b=Math.sin(b)*Math.sin(c);c=Math.sin(_.ud(a));var f=e*e*d*d+d*d*d*d-d*d*c*c;if(0>f)return null;var g=e*c+Math.sqrt(f);g/=d*d+e*e;var h=(c-e*g)/d;g=Math.atan2(h,g);if(g<-Math.PI/2||g>Math.PI/2)g=e*c-Math.sqrt(f),g=Math.atan2(h,g/(d*d+e*e));if(g<-Math.PI/2||g>Math.PI/2)return null;a=_.vd(a)-Math.atan2(b,d*Math.cos(g)-e*Math.sin(g));return new _.R(_.hc(g),_.hc(a))};
_.cb("Spherical.computeOffsetOrigin",ws.computeOffsetOrigin);ws.interpolate=function(a,b,c){var d=_.ud(a),e=_.vd(a),f=_.ud(b),g=_.vd(b),h=Math.cos(d),k=Math.cos(f);b=ws.gf(a,b);var l=Math.sin(b);if(1E-6>l)return new _.R(a.lat(),a.lng());a=Math.sin((1-c)*b)/l;c=Math.sin(c*b)/l;b=a*h*Math.cos(e)+c*k*Math.cos(g);e=a*h*Math.sin(e)+c*k*Math.sin(g);return new _.R(_.hc(Math.atan2(a*Math.sin(d)+c*Math.sin(f),Math.sqrt(b*b+e*e))),_.hc(Math.atan2(e,b)))};_.cb("Spherical.interpolate",ws.interpolate);
ws.gf=function(a,b){var c=_.ud(a);a=_.vd(a);var d=_.ud(b);b=_.vd(b);return 2*Math.asin(Math.sqrt(Math.pow(Math.sin((c-d)/2),2)+Math.cos(c)*Math.cos(d)*Math.pow(Math.sin((a-b)/2),2)))};ws.computeDistanceBetween=function(a,b,c){c=c||6378137;return ws.gf(a,b)*c};_.cb("Spherical.computeDistanceBetween",ws.computeDistanceBetween);ws.computeLength=function(a,b){b=b||6378137;var c=0;a instanceof _.je&&(a=a.getArray());for(var d=0,e=a.length-1;d<e;++d)c+=ws.computeDistanceBetween(a[d],a[d+1],b);return c};
_.cb("Spherical.computeLength",ws.computeLength);ws.computeArea=function(a,b){return Math.abs(ws.computeSignedArea(a,b))};_.cb("Spherical.computeArea",ws.computeArea);ws.computeSignedArea=function(a,b){b=b||6378137;a instanceof _.je&&(a=a.getArray());for(var c=a[0],d=0,e=1,f=a.length-1;e<f;++e)d+=ws.Dj(c,a[e],a[e+1]);return d*b*b};_.cb("Spherical.computeSignedArea",ws.computeSignedArea);ws.Dj=function(a,b,c){return ws.Ej(a,b,c)*ws.yk(a,b,c)};
ws.Ej=function(a,b,c){var d=[a,b,c,a];a=[];for(c=b=0;3>c;++c)a[c]=ws.gf(d[c],d[c+1]),b+=a[c];b/=2;d=Math.tan(b/2);for(c=0;3>c;++c)d*=Math.tan((b-a[c])/2);return 4*Math.atan(Math.sqrt(Math.abs(d)))};
ws.yk=function(a,b,c){a=[a,b,c];b=[];for(c=0;3>c;++c){var d=a[c],e=_.ud(d);d=_.vd(d);var f=b[c]=[];f[0]=Math.cos(e)*Math.cos(d);f[1]=Math.cos(e)*Math.sin(d);f[2]=Math.sin(e)}return 0<b[0][0]*b[1][1]*b[2][2]+b[1][0]*b[2][1]*b[0][2]+b[2][0]*b[0][1]*b[1][2]-b[0][0]*b[2][1]*b[1][2]-b[1][0]*b[0][1]*b[2][2]-b[2][0]*b[1][1]*b[0][2]?1:-1};var xs={decodePath:function(a){for(var b=_.L(a),c=Array(Math.floor(a.length/2)),d=0,e=0,f=0,g=0;d<b;++g){var h=1,k=0;do{var l=a.charCodeAt(d++)-63-1;h+=l<<k;k+=5}while(31<=l);e+=h&1?~(h>>1):h>>1;h=1;k=0;do l=a.charCodeAt(d++)-63-1,h+=l<<k,k+=5;while(31<=l);f+=h&1?~(h>>1):h>>1;c[g]=new _.R(1E-5*e,1E-5*f,!0)}c.length=g;return c}};_.cb("PolylineCodec.decodePath",xs.decodePath);
xs.encodePath=function(a){a instanceof _.je&&(a=a.getArray());return xs.Ml(a,function(b){return[Math.round(1E5*b.lat()),Math.round(1E5*b.lng())]})};_.cb("PolylineCodec.encodePath",xs.encodePath);xs.Ml=function(a,b){for(var c=[],d=[0,0],e,f=0,g=_.L(a);f<g;++f)e=b?b(a[f]):a[f],xs.Ph(e[0]-d[0],c),xs.Ph(e[1]-d[1],c),d=e;return c.join("")};xs.Ph=function(a,b){xs.Nl(0>a?~(a<<1):a<<1,b)};xs.Nl=function(a,b){for(;32<=a;)b.push(String.fromCharCode((32|a&31)+63)),a>>=5;b.push(String.fromCharCode(a+63))};_.y.google.maps.geometry={encoding:xs,spherical:ws,poly:vs};_.p=us.prototype;_.p.decodePath=xs.decodePath;_.p.encodePath=xs.encodePath;_.p.computeDistanceBetween=ws.computeDistanceBetween;_.p.interpolate=ws.interpolate;_.p.computeHeading=ws.computeHeading;_.p.computeOffset=ws.computeOffset;_.p.computeOffsetOrigin=ws.computeOffsetOrigin;_.Ne("geometry",new us);});
